In [26]:
import numpy as np

---

# Create

## Range

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Shape

In [28]:
arr = np.arange(12)
arr.shape = 4, 3
arr, arr.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

## From list

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr, arr.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

# Read

## Iterate

### N-Dimention as flatten

#### Simple

In [30]:
arr = np.arange(12).reshape(4, 3)

for i in np.nditer(arr):
    print(i)

np.nditer(arr), type(np.nditer(arr))

0
1
2
3
4
5
6
7
8
9
10
11


(<numpy.nditer at 0x1c0ea648210>, numpy.nditer)

#### With index

In [31]:
arr = np.arange(12).reshape(4, 3)

for index, i in np.ndenumerate(arr):
    print(index, i)

np.ndenumerate(arr), type(np.ndenumerate(arr))

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(3, 0) 9
(3, 1) 10
(3, 2) 11


(<numpy.ndenumerate at 0x1c0ea621810>, numpy.ndenumerate)

## Check

### All

In [39]:
arr = np.arange(1, 13).reshape(4, 3)

assert all(n > 0 for n in np.nditer(arr)) is True

### Type

In [32]:
type(np.array([1, 2, 3]))

numpy.ndarray

# Update

## Map

In [33]:
arr = np.arange(12).reshape(4, 3)

sqrt = lambda n: 2 ** n
vectorizedSqrt = np.vectorize(sqrt)

vectorizedSqrt(arr)

array([[   1,    2,    4],
       [   8,   16,   32],
       [  64,  128,  256],
       [ 512, 1024, 2048]])

In [34]:
np.arange(12) ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [35]:
2 ** np.arange(12)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024,
       2048], dtype=int32)

## Reshape

In [36]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Flatten

In [37]:
np.arange(12).reshape(4, 3).reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Convert

### List

In [38]:
list(np.array([1, 2, 3]))

[1, 2, 3]