In [14]:
import numpy as np

#### Numbers

In [4]:
a = 7
b = 7.0

print(a, type(a))
print(b, type(b))

7 <class 'int'>
7.0 <class 'float'>


#### Strings

In [18]:
name = 'Mark'
surname = 'Johnson'

print(name, type(name))

Mark <class 'str'>


#### String operations

In [46]:
print(name + ' ' + surname, type(name))
print(name + (' ' * 5) + surname)
print(name.find('a'), name.find('b'))

Mark Johnson <class 'str'>
Mark     Johnson
1 -1


#### Variables

In [8]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      7
b          float    7.0
name       str      Mark
surname    str      Johnson


#### Convert

In [13]:
print(int(7.5))
print(float(8))
print(str(9) + str(1))
print(int('5') + int('3'))

7
8.0
91
8


### Lists and Arrays

#### Lists

In [22]:
arr1 = [1, 2, 3]

print(arr1, type(arr))

[1, 2, 3] <class 'list'>


#### List operations

In [44]:
arr2 = [4, 5, 6]

print(arr1 + arr2)
print(arr1 * 2)
print(arr1[1:]) # from 1 till the end
print(arr1[:1]) # from start till 1
print(arr1[1:2])

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]
[2, 3]
[1]
[2]


#### Numpy array

In [29]:
npArr1 = np.array(arr1)

print(npArr1, type(npArr1))

[1 2 3] <class 'numpy.ndarray'>


#### Numpy array operations

In [31]:
npArr2 = np.array(arr2)

additionResult = npArr1 + npArr2
multiplicationResult = npArr1 * 2

print(additionResult, type(additionResult))
print(multiplicationResult, type(multiplicationResult))

[5 7 9] <class 'numpy.ndarray'>
[2 4 6] <class 'numpy.ndarray'>


#### Loops - enumerate

In [34]:
for index, letter in enumerate(name + ' ' + surname):
    print(index, letter)

0 M
1 a
2 r
3 k
4  
5 J
6 o
7 h
8 n
9 s
10 o
11 n
